Traveler/Areas/Admin/Controllers/SchedulesManageController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Traveler.Models;

namespace Traveler.Areas.Admin.Controllers
{
    public class SchedulesManageController : Controller
    {
        private TravelBookingEntities db = new TravelBookingEntities();

        // GET: Admin/SchedulesManage
        public ActionResult Index()
        {
            var schedules = db.Schedules.Include(s => s.Tour);
            return View(schedules.ToList());
        }

        // GET: Admin/SchedulesManage/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Schedule schedule = db.Schedules.Find(id);
            if (schedule == null)
            {
                return HttpNotFound();
            }
            return View(schedule);
        }

        // GET: Admin/SchedulesManage/Create
        public ActionResult Create(int? idTour)
        {
            ViewBag.Tour = db.Tours.FirstOrDefault(t => t.ID == idTour);

            ViewBag.TourID = new SelectList(db.Tours, "ID", "TourName");
            return View();
        }

        // POST: Admin/SchedulesManage/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,TourID,ScheduleName,ScheduleDetail")] Schedule schedule)
        {
            if (ModelState.IsValid)
            {
                db.Schedules.Add(schedule);
                db.SaveChanges();
                return RedirectToAction("Edit", "ToursManage", new { id = schedule.TourID });

            }

            ViewBag.TourID = new SelectList(db.Tours, "ID", "TourName", schedule.TourID);
            return View(schedule);
        }

        // GET: Admin/SchedulesManage/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Schedule schedule = db.Schedules.Find(id);
            if (schedule == null)
            {
                return HttpNotFound();
            }
            ViewBag.TourID = new SelectList(db.Tours, "ID", "TourName", schedule.TourID);
            return View(schedule);
        }

        // POST: Admin/SchedulesManage/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,TourID,ScheduleName,ScheduleDetail")] Schedule schedule)
        {
            if (ModelState.IsValid)
            {
                db.Entry(schedule).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Edit","ToursManage", new {id = schedule.TourID});
            }
            ViewBag.TourID = new SelectList(db.Tours, "ID", "TourName", schedule.TourID);
            return View(schedule);
        }

        // GET: Admin/SchedulesManage/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Schedule schedule = db.Schedules.Find(id);
            if (schedule == null)
            {
                return HttpNotFound();
            }
            return View(schedule);
        }

        // POST: Admin/SchedulesManage/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Schedule schedule = db.Schedules.Find(id);
            int? idTour = schedule.TourID;
            db.Schedules.Remove(schedule);
            db.SaveChanges();
            return RedirectToAction("Edit", "ToursManage", new { id = idTour });

        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Traveler/Areas/Admin/Controllers/ToursManageController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using Traveler.Design_Pattern.Command_Pattern;
using Traveler.FileExporter;
using Traveler.FileExporter.OptionExporter;
using Traveler.Models;

namespace Traveler.Areas.Admin.Controllers
{
    public class ToursManageController : Controller
    {
        private TravelBookingEntities db = new TravelBookingEntities();
        private TourData tourData;

        // GET: Admin/ToursManage
        public ActionResult Index()
        {
            var tours = db.Tours.Include(t => t.DepartureLocation).Include(t => t.Destination).Include(t => t.TourGuide);
            return View(tours.ToList());
        }

        // GET: Admin/ToursManage/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tour tour = db.Tours.Find(id);
            if (tour == null)
            {
                return HttpNotFound();
            }
            return View(tour);
        }

        // GET: Admin/ToursManage/Create
        public ActionResult Create()
        {
            ViewBag.DepartureLocationID = new SelectList(db.DepartureLocations, "ID", "DepartureName");
            ViewBag.DestinationID = new SelectList(db.Destinations, "ID", "DestinationName");
            ViewBag.TourGuideID = new SelectList(db.TourGuides, "ID", "TourGuideName");
            return View();
        }

        // POST: Admin/ToursManage/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Tour tour, HttpPostedFileBase Image1, HttpPostedFileBase Image2, HttpPostedFileBase Image3)
        {
            if (ModelState.IsValid)
            {
                DateTime parseDateTime;
                if (DateTime.TryParse(tour.DepartureDay.ToString(), out parseDateTime) && DateTime.TryParse(tour.EndDay.ToString(), out parseDateTime))
                {
                    if (Image1 != null)
                    {
                        var fileName = Path.GetFileName(Image1.FileName);
                        var path = Path.Combine(Server.MapPath("~/Content/img"), fileName);
                        tour.Image1 = fileName;
                        Image1.SaveAs(path);
                    }

                    if (Image2 != null)
                    {
                        var fileName = Path.GetFileName(Image2.FileName);
                        var path = Path.Combine(Server.MapPath("~/Content/img"), fileName);
                        tour.Image2 = fileName;
                        Image2.SaveAs(path);
                    }

                    if (Image3 != null)
                    {
                        var fileName = Path.GetFileName(Image3.FileName);
                        var path = Path.Combine(Server.MapPath("~/Content/img"), fileName);
                        tour.Image3 = fileName;
                        Image3.SaveAs(path);

                    }
                    db.Tours.Add(tour);
                    db.SaveChanges();

                    tourData = new TourData();
                    tourData.SetOption(new CreateOption());
                    tourData.ExportData(InputData(tour));
                }
                return RedirectToAction("Index");
            }

            ViewBag.DepartureLocationID = new SelectList(db.DepartureLocations, "ID", "DepartureName", tour.DepartureLocationID);
            ViewBag.DestinationID = new SelectList(db.Destinations, "ID", "DestinationName", tour.DestinationID);
            ViewBag.TourGuideID = new SelectList(db.TourGuides, "ID", "TourGuideName", tour.TourGuideID);

            return View(tour);
        }

        // GET: Admin/ToursManage/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Tour tour = db.Tours.Find(id);

            if (tour == null)
            {
                return HttpNotFound();
            }
            ITourCommand editCommand = new EditTourCommand(tour, db);

            editCommand.Execute();
            ViewBag.DepartureLocationID = new SelectList(db.DepartureLocations, "ID", "DepartureName", tour.DepartureLocationID);
            ViewBag.DestinationID = new SelectList(db.Destinations, "ID", "DestinationName", tour.DestinationID);
            ViewBag.TourGuideID = new SelectList(db.TourGuides, "ID", "TourGuideName", tour.TourGuideID);

            ViewBag.Schedule = db.Schedules.Where(s => s.TourID == id).ToList();
            return View(tour);
        }

        // POST: Admin/ToursManage/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,TourName,DestinationID,SlotNumber,DepartureDay,EndDay,DepartureLocationID,Price,Hotel,ViewNumber,GatherPlace,TourGuideID,Image1,Image2,Image3,TourDescription")] Tour tour)
        {
            if (ModelState.IsValid)
            { 
                db.Entry(tour).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            tourData = new TourData();
            tourData.SetOption(new EditOption());
            tourData.ExportData(InputData(tour));

            ViewBag.DepartureLocationID = new SelectList(db.DepartureLocations, "ID", "DepartureName", tour.DepartureLocationID);
            ViewBag.DestinationID = new SelectList(db.Destinations, "ID", "DestinationName", tour.DestinationID);
            ViewBag.TourGuideID = new SelectList(db.TourGuides, "ID", "TourGuideName", tour.TourGuideID);
            return View(tour);
        }

        // GET: Admin/ToursManage/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tour tour = db.Tours.Find(id);
            if (tour == null)
            {
                return HttpNotFound();
            }
            return View(tour);
        }

        // POST: Admin/ToursManage/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Tour tour = db.Tours.Find(id);
            db.Tours.Remove(tour);
            db.SaveChanges();

            tourData = new TourData();
            tourData.SetOption(new DeleteOption());
            tourData.ExportData(InputData(tour));

            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public TourData InputData(Tour tour)
        {
            int id;
            string tourName, desBegin, desEnd, maxCus, dateBegin, dateEnd, price, hotel, meeting, tourGuide, description;

            id = tour.ID;
            tourName = tour.TourName.ToString();
            desBegin = (from des in db.DepartureLocations where des.ID == tour.DepartureLocationID select des.DepartureName).SingleOrDefault();
            desEnd = (from des in db.Destinations where des.ID == tour.DestinationID select des.DestinationName).SingleOrDefault();
            maxCus = tour.SlotNumber.ToString();
            dateBegin = tour.DepartureDay?.ToString("dd/MM/yyyy");
            dateEnd = tour.EndDay?.ToString("dd/MM/yyyy");
            price = tour.Price.ToString();
            hotel = tour.Hotel.ToString();
            meeting = tour.GatherPlace.ToString();
            tourGuide = (from tg in db.TourGuides where tg.ID == tour.TourGuideID select tg.TourGuideName).SingleOrDefault();
            description = tour.TourDescription.ToString();

            tourData = new TourData(id, tourName, desBegin, desEnd, maxCus, dateBegin, dateEnd, price, hotel, meeting, tourGuide, description);
            return tourData;
        }
    }
}

Traveler/Areas/Admin/Views/ToursManage/Create.cshtml
@model Traveler.Models.Tour

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/ViewPage1.cshtml";
}

<h2>Create</h2>
<style>
    .checkbox-img {
        display: flex;
    }
</style>

@using (Html.BeginForm("Create", "ToursManage", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Tour</h4>
        <hr />
        <div class="form-group">
            <div class="col-lg-2"></div>

            <div class="col-md-10">
                <div class="checkbox-img">
                    <div class="box-img-admin">
                        <img id="blah" src="#" alt="" width="80px" height="80px" /><br>
                        <input accept="image/*" type='file' id="imgInp" name="Image1" />
                        <label for="imgInp"><i class="bi bi-upload">Hình 1</i></label>
                    </div>
                    <div class="box-img-admin">
                        <img id="bleh" src="#" alt="" width="80px" height="80px" /><br>
                        <input accept="image/*" type='file' id="imgImp" name="Image2" />
                        <label for="imgImp"><i class="bi bi-upload">Hình 2</i></label>

                    </div>
                    <div class="box-img-admin">
                        <img id="bldh" src="#" alt="" width="80px" height="80px" /><br>
                        <input accept="image/*" type='file' id="imgIop" name="Image3" />
                        <label for="imgIop"><i class="bi bi-upload">Hình 3</i></label>

                    </div>
                </div>
            </div>

        </div>


        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <label class="control-label col-md-2">Tiêu đề Tour</label>

            <div class="col-md-10">
                @Html.EditorFor(model => model.TourName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TourName, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2">Điểm đi</label>

            <div class="col-md-10">
                @Html.DropDownList("DepartureLocationID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.DepartureLocationID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Điểm đến</label>

            <div class="col-md-10">
                @Html.DropDownList("DestinationID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.DestinationID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Số lượng khách</label>

            <div class="col-md-10">
                @Html.EditorFor(model => model.SlotNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SlotNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Ngày khởi hành</label>

            <div class="col-md-10">
                @Html.EditorFor(model => model.DepartureDay, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DepartureDay, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Đến ngày</label>

            <div class="col-md-10">
                @Html.EditorFor(model => model.EndDay, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EndDay, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group">
            <label class="control-label col-md-2">Giá</label>

            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Khách sạn</label>

            <div class="col-md-10">
                @Html.EditorFor(model => model.Hotel, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Hotel, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group">
            <label class="control-label col-md-2">Địa điểm tập trung</label>

            <div class="col-md-10">
                @Html.EditorFor(model => model.GatherPlace, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GatherPlace, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Hướng dẫn đoàn</label>

            <div class="col-md-10">
                @Html.DropDownList("TourGuideID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TourGuideID, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group">
            <label class="control-label col-md-2">Mô tả</label>

            <div class="col-md-10">
                <textarea class="form-control" name="TourDescription"></textarea>

                @Html.ValidationMessageFor(model => model.TourDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Traveler/Areas/Admin/Views/ToursManage/Delete.cshtml
@model Traveler.Models.Tour

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/ViewPage1.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Tour</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TourName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TourName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SlotNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SlotNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DepartureDay)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DepartureDay)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndDay)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndDay)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Hotel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Hotel)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ViewNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ViewNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GatherPlace)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GatherPlace)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Image1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Image2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image3)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Image3)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TourDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TourDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DepartureLocation.DepartureName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DepartureLocation.DepartureName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Destination.DestinationName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Destination.DestinationName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TourGuide.TourGuideName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TourGuide.TourGuideName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Traveler/Areas/Admin/Views/ToursManage/Edit.cshtml
@model Traveler.Models.Tour

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/ViewPage1.cshtml";
}
<style>
    .checkbox-img {
        display: flex;
    }
</style>

<h2>Chỉnh sửa</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)


        <div class="form-group">
            <div class="col-lg-2"></div>

            <div class="col-md-10">
                <div class="checkbox-img">
                    <div class="box-img-admin">
                        <img id="blah" src="~/Content/img/@Model.Image1" alt="" width="80px" height="80px" /><br>
                        <input accept="image/*" type='file' id="imgInp" name="Image1" />
                        <label for="imgInp"><i class="bi bi-upload">Hình 1</i></label>
                    </div>
                    <div class="box-img-admin">
                        <img id="bleh" src="~/Content/img/@Model.Image2" alt="" width="80px" height="80px" /><br>
                        <input accept="image/*" type='file' id="imgImp" name="Image2" />
                        <label for="imgImp"><i class="bi bi-upload">Hình 2</i></label>

                    </div>
                    <div class="box-img-admin">
                        <img id="bldh" src="~/Content/img/@Model.Image3" alt="" width="80px" height="80px" /><br>
                        <input accept="image/*" type='file' id="imgIop" name="Image3" />
                        <label for="imgIop"><i class="bi bi-upload">Hình 3</i></label>

                    </div>
                </div>
            </div>

        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Tiêu đề Tour</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.TourName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TourName, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2">Điểm đi</label>

            <div class="col-md-10">
                @Html.DropDownList("DepartureLocationID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.DepartureLocationID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">


            <label class="control-label col-md-2">Điểm đến</label>

            <div class="col-md-10">
                @Html.DropDownList("DestinationID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.DestinationID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Số lượng khách</label>

            <div class="col-md-10">
                @Html.EditorFor(model => model.SlotNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SlotNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Ngày khởi hành</label>

            <div class="col-md-10">
                @Html.EditorFor(model => model.DepartureDay, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DepartureDay, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Đến ngày</label>

            <div class="col-md-10">
                @Html.EditorFor(model => model.EndDay, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EndDay, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group">
            <label class="control-label col-md-2">Giá</label>

            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Khách sạn</label>

            <div class="col-md-10">
                @Html.EditorFor(model => model.Hotel, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Hotel, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
                @Html.LabelFor(model => model.ViewNumber, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ViewNumber, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ViewNumber, "", new { @class = "text-danger" })
                </div>
            </div>*@
        <input type="hidden" value="@Model.ViewNumber" disabled name="ViewNumber" class="form-control" />

        <div class="form-group">
            <label class="control-label col-md-2">Địa điểm tập trung</label>

            <div class="col-md-10">
                @Html.EditorFor(model => model.GatherPlace, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GatherPlace, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Hướng dẫn đoàn</label>

            <div class="col-md-10">
                @Html.DropDownList("TourGuideID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TourGuideID, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group">
            <label class="control-label col-md-2">Mô tả</label>

            <div class="col-md-10">
                <textarea class="form-control" name="TourDescription">@Model.TourDescription</textarea>
                @Html.ValidationMessageFor(model => model.TourDescription, "", new { @class = "text-danger" })
            </div>
        </div>
        <hr />

        <div class="container">
            <h4>Lịch trình : </h4>
            <button type="button" class="btn btn-success" onclick="location.href='@Url.Action("Create", "SchedulesManage",new {idTour = Model.ID })'">Thêm lịch trình</button>

            @foreach (var item in ViewBag.Schedule)
            {
                <div class="form-group">
                    <label class="control-label col-md-2">@item.ScheduleName</label>

                    <div class="col-md-10">
                        <p>@item.ScheduleDetail</p>
                        <button type="button" class="btn btn-info" onclick="location.href='@Url.Action("Edit", "SchedulesManage",new {id = item.ID })'"> Chỉnh sửa</button>
                        <button type="button" class="btn btn-danger" onclick="location.href='@Url.Action("Delete", "SchedulesManage",new {id = item.ID })'">Xóa</button>

                    </div>

                </div>
                <hr />
            }

        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Lưu" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Quay lại danh sách", "Index")
</div>