Traveler/Controllers/HomeController.cs
//using System;
//using System.Collections.Generic;
//using System.Linq;
//using System.Web;
//using System.Web.Mvc;
//using Traveler.Models;

//namespace Traveler.Controllers
//{
//    public class HomeController : Controller
//    {
//        TravelBookingEntities db = new TravelBookingEntities();
//        public ActionResult Index()
//        {
//            ViewBag.TourGuidesList = db.TourGuides.ToList();
//            List<Tour> toursList = db.Tours.ToList();
//            toursList.Reverse();
//            ViewBag.ToursList = toursList;
//            ViewBag.DestinationLst = db.Destinations.ToList();
//            ViewBag.DepartureLocationLst = db.DepartureLocations.ToList();

//            return View();
//        }

//        public ActionResult TourPackage()
//        {
//            ViewBag.TourGuidesList = db.TourGuides.ToList();
//            List<Tour> toursList = db.Tours.ToList();
//            toursList.Reverse();
//            ViewBag.ToursList = toursList;
//            ViewBag.DestinationLst = db.Destinations.ToList();
//            ViewBag.DepartureLocationLst = db.DepartureLocations.ToList();
//            return View();
//        }
using System.Web.Mvc;
using Traveler.Design_Pattern.Facade_Pattern;


namespace Traveler.Controllers
{
    public class HomeController : Controller
    {
        private TravelFacade _travelFacade = new TravelFacade();

        public ActionResult Index()
        {
            ViewBag.TourGuidesList = _travelFacade.GetTourGuides();
            ViewBag.ToursList = _travelFacade.GetTours();
            ViewBag.DestinationLst = _travelFacade.GetDestinations();
            ViewBag.DepartureLocationLst = _travelFacade.GetDepartureLocations();

            return View();
        }
        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Traveler/Controllers/TourSearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Traveler.Design_Pattern.Factory_Pattern;
using Traveler.Models;

namespace Traveler.Controllers
{
    public class TourSearchController : Controller
    {
        TravelBookingEntities db = new TravelBookingEntities();

        [HttpGet]
        // GET: TourSearch
        public ActionResult FillResult()
        {
            return View();
        }

        [HttpPost]
        // GET: TourSearch
        public ActionResult FillResult(FormCollection form)
        {
            //    string departureLocation = form["DepartureLocation"].ToString().Trim();
            //    string destination = form["Destination"].ToString().Trim();
            //    string departureDayString = form["DepartureDay"];
            //    int durationType = int.Parse(form["PriceRange"]);
            //    DateTime departureDay;
            //    var inteval = (0,0);

            //    switch (durationType)
            //    {
            //        case 1: { inteval = (1, 3); break; }
            //        case 2: { inteval = (4, 7); break; }
            //        case 3: { inteval = (8, 100); break; }
            //        default: { inteval = (0,100); break; }
            //    }

            //    //if(departureLocation == null)
            //    //{

            //    //}

            //    if (DateTime.TryParse(departureDayString, out departureDay))
            //    {
            //        departureDay = DateTime.Parse(departureDayString);
            //        var lstTour = db.Tours
            //            .Where(t => t.DepartureLocation.DepartureName.Contains(departureLocation) &&
            //            t.Destination.DestinationName.Contains(destination) &&
            //            (departureDay == null || t.DepartureDay == departureDay) &&                    
            //            t.Price >= inteval.Item1*1000000 && t.Price <= inteval.Item2*1000000).ToList();

            //        ViewBag.ToursList = lstTour;

            //    }
            //    else
            //    {
            //        ViewBag.ToursList = db.Tours.Where(t => t.DepartureLocation.DepartureName.Contains(departureLocation) && t.Destination.DestinationName.Contains(destination) && t.Price >= inteval.Item1 * 1000000 && t.Price <= inteval.Item2 * 1000000).ToList();

            //    }





            //    return View();
            //}
            string departureLocation = form["DepartureLocation"].ToString().Trim();
            string destination = form["Destination"].ToString().Trim();
            string departureDayString = form["DepartureDay"];
            int durationType = int.Parse(form["PriceRange"]);
            DateTime departureDay;
            var interval = (0, 0);

            switch (durationType)
            {
                case 1: { interval = (1, 3); break; }
                case 2: { interval = (4, 7); break; }
                case 3: { interval = (8, 100); break; }
                default: { interval = (0, 100); break; }
            }

            ITourSearchFactory searchFactory;
            if (DateTime.TryParse(departureDayString, out departureDay))
            {
                searchFactory = new DepartureDayTourSearchFactory();
            }
            else
            {
                searchFactory = new DefaultTourSearchFactory();
            }

            var lstTour = searchFactory.SearchTours(db, departureLocation, destination, departureDay, interval);
            ViewBag.ToursList = lstTour;

            return View();
        }
    }
}

Traveler/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Traveler/Views/Home/Index.cshtml
@{
    var formatMoney = System.Globalization.CultureInfo.GetCultureInfo("vi-VN");
}
    
    <!-- Carousel Start -->
<div class="container-fluid p-0">
    <div id="header-carousel" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img class="w-100" src="~/Content/img/carousel-1.jpg" alt="Image">
                <div class="carousel-caption d-flex flex-column align-items-center justify-content-center">
                    <div class="p-3" style="max-width: 900px;">
                        <h4 class="text-white text-uppercase mb-md-3">Tours & Travel</h4>
                        <h1 class="display-3 text-white mb-md-4">Let's Discover The World Together</h1>
                        <a href="" class="btn btn-primary py-md-3 px-md-5 mt-2">Book Now</a>
                    </div>
                </div>
            </div>
            <div class="carousel-item">
                <img class="w-100" src="~/Content/img/carousel-2.jpg" alt="Image">
                <div class="carousel-caption d-flex flex-column align-items-center justify-content-center">
                    <div class="p-3" style="max-width: 900px;">
                        <h4 class="text-white text-uppercase mb-md-3">Tours & Travel</h4>
                        <h1 class="display-3 text-white mb-md-4">Discover Amazing Places With Us</h1>
                        <a href="" class="btn btn-primary py-md-3 px-md-5 mt-2">Book Now</a>
                    </div>
                </div>
            </div>
        </div>
        <a class="carousel-control-prev" href="#header-carousel" data-slide="prev">
            <div class="btn btn-dark" style="width: 45px; height: 45px;">
                <span class="carousel-control-prev-icon mb-n2"></span>
            </div>
        </a>
        <a class="carousel-control-next" href="#header-carousel" data-slide="next">
            <div class="btn btn-dark" style="width: 45px; height: 45px;">
                <span class="carousel-control-next-icon mb-n2"></span>
            </div>
        </a>
    </div>
</div>
<!-- Carousel End -->
<!-- Booking Start -->
<div class="container-fluid booking mt-5 pb-5">
    @using (Html.BeginForm("FillResult", "TourSearch", FormMethod.Post))
    {
        @Html.ValidationSummary(true)
        <div class="container pb-5">
            <div class="bg-light shadow" style="padding: 30px;">
                <div class="row align-items-center" style="min-height: 60px;">
                    <div class="col-md-10">
                        <div class="row">
                            <div class="col-md-3">
                                <div class="mb-3 mb-md-0">
                                    <small>Điểm đi</small>
                                    <select name="DepartureLocation" class="custom-select px-4" style="height: 47px;">
                                        <option value="">Điểm đi của bạn</option>
                                        @foreach (var item in ViewBag.DepartureLocationLst)
                                        {
                                            <option value="@item.DepartureName">@item.DepartureName</option>
                                        }
                                    </select>
                                </div>
                            </div>

                            <div class="col-md-3">
                                <div class="mb-3 mb-md-0">
                                    <small>Điểm đến</small>
                                    <select name="Destination" class="custom-select px-4" style="height: 47px;">
                                        <option value="">Điểm đến của bạn</option>
                                        @foreach (var item in ViewBag.DestinationLst)
                                        {
                                            <option value="@item.DestinationName">@item.DestinationName</option>
                                        }
                                    </select>
                                </div>
                            </div>
                            <div class="col-md-3">
                                <div class="mb-3 mb-md-0">
                                    <div class="date" id="date1" data-target-input="nearest">
                                        <small>Ngày đi</small>

                                        <input name="DepartureDay" type="text" class="form-control p-4 datetimepicker-input" placeholder="Depart Date" data-target="#date1" data-toggle="datetimepicker" />
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-3">
                                <div class="mb-3 mb-md-0">
                                    <div class="date" id="date2" data-target-input="nearest">
                                        <small>Giá</small>
                                        <select name="PriceRange" class="custom-select px-4" style="height: 47px;">
                                            <option value="0">Tất cả</option>
                                            <option value="1">1 triệu -3 triệu</option>
                                            <option value="2">4 triệu - 7 triệu</option>
                                            <option value="3">Trên 7 triệu</option>
                                        </select>
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>
                    <div class="col-md-2">
                        <small> &nbsp;</small>
                        <button class="btn btn-primary btn-block" type="submit" style="height: 47px; margin-top: -2px;">Submit</button>
                    </div>
                </div>
            </div>
        </div>

    }
    </div>
<!-- Booking End -->

<!-- Feature Start -->
<div class="container-fluid pb-5">
    <div class="container pb-5">
        <div class="row">
            <div class="col-md-4">
                <div class="d-flex mb-4 mb-lg-0">
                    <div class="d-flex flex-shrink-0 align-items-center justify-content-center bg-primary mr-3" style="height: 100px; width: 100px;">
                        <i class="fa fa-2x fa-money-check-alt text-white"></i>
                    </div>
                    <div class="d-flex flex-column">
                        <h5 class="">Competitive Pricing</h5>
                        <p class="m-0">Magna sit magna dolor duo dolor labore rebum amet elitr est diam sea</p>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="d-flex mb-4 mb-lg-0">
                    <div class="d-flex flex-shrink-0 align-items-center justify-content-center bg-primary mr-3" style="height: 100px; width: 100px;">
                        <i class="fa fa-2x fa-award text-white"></i>
                    </div>
                    <div class="d-flex flex-column">
                        <h5 class="">Best Services</h5>
                        <p class="m-0">Magna sit magna dolor duo dolor labore rebum amet elitr est diam sea</p>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="d-flex mb-4 mb-lg-0">
                    <div class="d-flex flex-shrink-0 align-items-center justify-content-center bg-primary mr-3" style="height: 100px; width: 100px;">
                        <i class="fa fa-2x fa-globe text-white"></i>
                    </div>
                    <div class="d-flex flex-column">
                        <h5 class="">Worldwide Coverage</h5>
                        <p class="m-0">Magna sit magna dolor duo dolor labore rebum amet elitr est diam sea</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Feature End -->

<!-- Packages Start -->
<div class="container-fluid py-5">
    <div class="container pt-5 pb-3">
        <div class="text-center mb-3 pb-3">
            <h6 class="text-primary text-uppercase" style="letter-spacing: 5px;">TOUR</h6>
            <h1>KHÁM PHÁ TOUR DU LỊCH CỦA TRAVELER</h1>
        </div>
        <div class="row">

            @foreach (var item in ViewBag.ToursList)
            {
                <div class="col-lg-4 col-md-6 mb-4">
                    <div class="package-item bg-white mb-2">
                        <img class="img-fluid" src="~/Content/img/@item.Image1" alt="">
                        <div class="p-4">
                            <div class="d-flex justify-content-between mb-3">
                                <small class="m-0"><i class="fa fa-map-marker-alt text-primary mr-2"></i>@item.Destination.DestinationName</small>
                                @{
                                    TimeSpan daysNumber = item.EndDay - item.DepartureDay;
                                    int day = daysNumber.Days;

                                    if (day > 0)
                                    {
                                        <small class="m-0"><i class="fa fa-calendar-alt text-primary mr-2"></i>@day ngày</small>
                                    }
                                    else
                                    {
                                        <small class="m-0"><i class="fa fa-calendar-alt text-primary mr-2"></i>Đã hết hạn</small>
                                    }
                                }

                                <small class="m-0"><i class="fa fa-user text-primary mr-2"></i>Còn lại: @item.SlotNumber chỗ</small>
                            </div>
                            @{

                                int maxLength = 50;

                                if (item.TourName.Length > maxLength)
                                {

                                    string truncatedTourName = item.TourName.Substring(0, maxLength) + "...";

                                    <a class="h5 text-decoration-none" href="@Url.Action("Detail/"+item.ID,"Tours")">@truncatedTourName</a>
                                }
                                else
                                {
                                    <a class="h5 text-decoration-none" href="@Url.Action("Detail/"+item.ID,"Tours")">@item.TourName</a>
                                }
                            }
                            <div class="border-top mt-4 pt-4">
                                <div class="d-flex justify-content-between">
                                    <h6 class="m-0"><i class="fa fa-star text-primary mr-2"></i>4.5 <small>(250)</small></h6>
                                    <h5 class="m-0">@String.Format(formatMoney, "{0:c0}", item.Price)</h5>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            }
        </div>
    </div>
</div>
<!-- Packages End -->

<!-- Team Start -->
<div class="container-fluid py-5">
    <div class="container pt-5 pb-3">
        <div class="text-center mb-3 pb-3">
            <h6 class="text-primary text-uppercase" style="letter-spacing: 5px;">Hướng dẫn viên</h6>
            <h1>Hướng dẫn viên du lịch của chúng tôi</h1>
        </div>
        <div class="row">

            @foreach (var item in ViewBag.TourGuidesList)
            {
                <div class="col-lg-3 col-md-4 col-sm-6 pb-2">
                    <div class="team-item bg-white mb-4">
                        <div class="team-img position-relative overflow-hidden">
                            <img class="img-fluid w-100" src="~/Content/img/@item.AvatarImage" alt="">
                            <div class="team-social">
                                <a class="btn btn-outline-primary btn-square" href=""><i class="fab fa-twitter"></i></a>
                                <a class="btn btn-outline-primary btn-square" href=""><i class="fab fa-facebook-f"></i></a>
                                <a class="btn btn-outline-primary btn-square" href=""><i class="fab fa-instagram"></i></a>
                                <a class="btn btn-outline-primary btn-square" href=""><i class="fab fa-linkedin-in"></i></a>
                            </div>
                        </div>
                        <div class="text-center py-4">
                            <h5 class="text-truncate">@item.TourGuideName</h5>
                            <p class="m-0">@item.TourGuideEmail</p>
                        </div>
                    </div>
                </div>
            }


            
        </div>
    </div>
</div>
<!-- Team End -->